name: Playwright Tests
on:
  # Condition A: Execute on Push and Pull Request (standard CI/CD)
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Condition B: Execute on a Scheduled Time
  schedule:
    - cron: '0 3 * * *'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    # 1. Install pnpm and clean dependencies
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 10.17.0
        run_install: true
    # 2. Install Playwright browsers
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    # 3. Run tests
    - name: Run Playwright tests
      run: pnpm exec playwright test
    # 4. Upload the report
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30